export const REQUEST_CARDS = 'GET/REQUEST_CARDS';
export const FETCH_CARDS = 'POST/FETCH_CARDS';
export const ADD_PRODUCT = 'CART/ADD_PRODUCT';
export const REMOVE_PRODUCT = 'CART/REMOVE_PRODUCT';
export const TOTAL_PRODUCTS = 'CART/TOTAL_PRODUCTS'; 
export const GET_TOTAL = 'CART/GET_TOTAL';